spring:
  application:
    name: propagandus-persistence

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/propagandus}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL:create}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}
    listener:
      simple:
        concurrency: ${RABBITMQ_CONCURRENCY:1}
        max-concurrency: ${RABBITMQ_MAX_CONCURRENCY:5}
        acknowledge-mode: ${RABBITMQ_ACK_MODE:auto}
    template:
      mandatory: true

  jackson:
    default-property-inclusion: non_null

server:
  port: ${APP_PORT:50000}

logging:
  level:
    org.springframework.amqp: INFO
    org.springframework.amqp.rabbit.connection: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE