server:
  port: 41004

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:43353/data-painel
    username: propagandus
    password: propagandus
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  data:
    mongodb:
      uri: mongodb://painel:painel@mongodb-painel:57053/painel-db
