server:
  port: 41005

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:53300/data-analitics
    username: propagandus
    password: propagandus
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true