version: "3.9"

services:
  mongodb-advertising:
    image: mongo:latest
    container_name: data-advertising
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: advertising
      MONGO_INITDB_ROOT_PASSWORD: advertising
    ports:
      - "57050:27017"
    volumes:
      - mongo_advertising_data:/data/db
    networks:
      - propagandus
  
  mongodb-attention:
    image: mongo:latest
    container_name: data-attention
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: attention
      MONGO_INITDB_ROOT_PASSWORD: attention
    ports:
      - "57051:27017"
    volumes:
      - mongo_attention_data:/data/db
    networks:
      - propagandus
    
  mongodb-location:
    image: mongo:latest
    container_name: data-location
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: location
      MONGO_INITDB_ROOT_PASSWORD: location
    ports:
      - "57052:27017"
    volumes:
      - mongo_location_data:/data/db
    networks:
      - propagandus

  mongodb-order:
    image: mongo:latest
    container_name: data-order
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: order
      MONGO_INITDB_ROOT_PASSWORD: order
    ports:
      - "57053:27017"
    volumes:
      - mongo_order_data:/data/db
    networks:
      - propagandus
  
  mongodb-painel:
    image: mongo:latest
    container_name: data-painel
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: painel
      MONGO_INITDB_ROOT_PASSWORD: painel
    ports:
      - "57054:27017"
    volumes:
      - mongo_painel_data:/data/db
    networks:
      - propagandus

  mongodb-period-register:
    image: mongo:latest
    container_name: data-period-register
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: period-register
      MONGO_INITDB_ROOT_PASSWORD: period-register
    ports:
      - "57055:27017"
    volumes:
      - mongo_period_register_data:/data/db
    networks:
      - propagandus

volumes:
  mongo_advertising_data:
  mongo_attention_data:
  mongo_location_data:
  mongo_order_data:
  mongo_painel_data:
  mongo_period_register_data:

networks:
  propagandus:
    driver: bridge