server:
  port: 41006

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:43355/data-reaction
    username: propagandus
    password: propagandus
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  data:
    mongodb:
      uri: mongodb://reaction:reaction@mongodb-reaction:57055/reaction-db