services:
  propagandus-app:
    build: .
    container_name: propagandus-app
    ports:
      - "50001:50001"
    volumes:
      - ./data:/app/data  # persistência do arquivo SQLite
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/data/propagandus.db
    depends_on:
      - postgres
      - redis
      - rabbitmq

  postgres:
    image: postgres:14-alpine
    container_name: propagandus-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: propagandus
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: propagandus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "25082:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    command: >
      rabbitmq-server
      --load_definitions=/etc/rabbitmq/definitions.json

volumes:
  pgdata:
  redis_data:
  rabbitmq_data: