version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "25082:15672"   # UI do RabbitMQ
      - "5672:5672"     # Comunicação AMQP
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    command: >
      rabbitmq-server
      --load_definitions=/etc/rabbitmq/definitions.json

  mongo:
    image: mongo:7.0
    container_name: propagandus-mongo
    ports:
      - "15081:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: propagandus_user
      MONGO_INITDB_ROOT_PASSWORD: propagandus_pass
      MONGO_INITDB_DATABASE: propagandus_db
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:14-alpine
    container_name: propagandus-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: propagandus
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: propagandus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8001:8001"     # Acesso via navegador
    depends_on:
      - redis

volumes:
  pgdata:
  mongo_data:
  rabbitmq_data:
  redis_data: