server:
  port: 40001

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:53301}/${DB_NAME:data-backup}
    username: ${USERNAME:propagandus}
    password: ${PASSWORD:propagandus2@}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true