spring:
  application:
    name: propagandus-local

  # Configurações do banco de dados
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:15081/propagandusdb

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 1
        max-concurrency: 5
        acknowledge-mode: auto
    template:
      mandatory: true

  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org.springframework.amqp: INFO
    org.springframework.amqp.rabbit.connection: INFO

server:
  port: 50001