spring:
  application:
    name: propagandus-local
    constants:
      localId: ${LOCAL_ID:66eb7688-c499-4821-a4b7-7ca92d7975b7}
      secret-key: ${JWT_SECRET_KEY:Y3Vyc28tYXV0ZW50aWNhY2FvLXN0YXRlZnVsLXN0YXRlbGVzcy1taWNyb3NzZXJ2aWNvcw==}
      token: ${TOKEN:dbfb45cf-5aa3-48f7-8ad9-47f592c9e6b}

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://propagandus_user:propagandus_pass@localhost:15081/propagandus_db?authSource=admin}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}
    listener:
      simple:
        concurrency: ${RABBITMQ_CONCURRENCY:1}
        max-concurrency: ${RABBITMQ_MAX_CONCURRENCY:5}
        acknowledge-mode: ${RABBITMQ_ACK_MODE:auto}
    template:
      mandatory: true

  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org.springframework.amqp: INFO
    org.springframework.amqp.rabbit.connection: INFO

server:
  port: ${APP_PORT:50001}