spring:
  application:
    name: propagandus-local
    constantes:
      localId: ${LOCAL_ID:6b04aefb-d2c6-487e-ba74-bd0f427e2ce8}

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://propagandus_user:propagandus_pass@localhost:15081/propagandus_db?authSource=admin}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}
    listener:
      simple:
        concurrency: ${RABBITMQ_CONCURRENCY:1}
        max-concurrency: ${RABBITMQ_MAX_CONCURRENCY:5}
        acknowledge-mode: ${RABBITMQ_ACK_MODE:auto}
    template:
      mandatory: true

  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org.springframework.amqp: INFO
    org.springframework.amqp.rabbit.connection: INFO

server:
  port: ${APP_PORT:50001}