server:
  port: 41001

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:43350/data-analytics
    username: propagandus
    password: propagandus
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  data:
    mongodb:
      uri: mongodb://analytics:analytics@mongodb-analytics:47050/analytics-db
