server:
  port: 60003

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:63310/data-persistence-service
    username: propagandus
    password: propagandus
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
  data:
    mongodb:
      uri: mongodb://sender:sender@mongodb-sender:61000/sender-db