version: '3.8'

services:
  mariadb-persistence:
    image: mariadb:latest
    container_name: data-persistence-service
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: data-persistence-service2@
      MARIADB_DATABASE: data-persistence-service
      MARIADB_USER: propagandus
      MARIADB_PASSWORD: propagandus
    ports:
      - "53310:3306"
    volumes:
      - mariadb_persistence_data:/var/lib/mysql
    networks:
      - propagandus

  redis-sender:
    image: redis:latest
    container_name: data-sender
    restart: always
    ports:
      - "63790:6379"
    volumes:
      - redis_sender_data:/data
    networks:
      - propagandus
  
  redis-persistence:
    image: redis:latest
    container_name: data-persistence-queue
    restart: always
    ports:
      - "63791:6379"
    volumes:
      - redis_persistence_data:/data
    networks:
      - propagandus

  redis-register:
    image: redis:latest
    container_name: data-register
    restart: always
    ports:
      - "63792:6379"
    volumes:
      - redis_register_data:/data
    networks:
      - propagandus

volumes:
  mariadb_persistence_data:
  redis_sender_data:
  redis_persistence_data:
  redis_register_data:

networks:
  propagandus:
    driver: bridge