version: '3.8'

services:
  mariadb-persistence:
    image: mariadb:latest
    container_name: data-persistence-service
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: data-persistence-service
      MARIADB_DATABASE: data-persistence-service
      MARIADB_USER: propagandus
      MARIADB_PASSWORD: propagandus
    ports:
      - "63310:3306"
    volumes:
      - mariadb_persistence_data:/var/lib/mysql
    networks:
      - propagandus

  mongodb-sender:
    image: mongo:latest
    container_name: data-sender
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sender
      MONGO_INITDB_ROOT_PASSWORD: sender
      MONGO_INITDB_DATABASE: sender-db
    ports:
      - "61000:27017"
    volumes:
      - mongo_sender_data:/data
    networks:
      - propagandus
  
  mongodb-persistence:
    image: mongo:latest
    container_name: data-persistence
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: persistence
      MONGO_INITDB_ROOT_PASSWORD: persistence
      MONGO_INITDB_DATABASE: persistence-db
    ports:
      - "61001:27017"
    volumes:
      - mongo_persistence_data:/data
    networks:
      - propagandus

  mongodb-register:
    image: mongo:latest
    container_name: data-register
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: register
      MONGO_INITDB_ROOT_PASSWORD: register
      MONGO_INITDB_DATABASE: register-db
    ports:
      - "61002:27017"
    volumes:
      - mongo_register_data:/data
    networks:
      - propagandus

volumes:
  mariadb_persistence_data:
  mongo_sender_data:
  mongo_persistence_data:
  mongo_register_data:

networks:
  propagandus:
    driver: bridge