version: '3.8'

services:
  mysql-persistence:
    image: mysql:latest
    container_name: data-persistence-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: data-persistence-service2@
      MYSQL_DATABASE: data-persistence-service
      MYSQL_USER: propagandus
      MYSQL_PASSWORD: propagandus2@
    ports:
      - "53310:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb-sender:
    image: mongo:latest
    container_name: sender-service
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sender-service
      MONGO_INITDB_ROOT_PASSWORD: sender-service
      MONGO_INITDB_DATABASE: sender-service-db
    ports:
      - "57011:27017"
    volumes:
      - mongo_sender:/data/db/sender-service
    networks:
      - propagandus
  
  redis-persistence:
    image: redis:latest
    container_name: data-persistence-queue
    restart: always
    ports:
      - "63791:6379"
    volumes:
      - redis_persistence_data:/data
    networks:
      - propagandus

  redis-people-register:
    image: redis:latest
    container_name: people-register
    restart: always
    ports:
      - "63792:6379"
    volumes:
      - redis_people_register_data:/data
    networks:
      - propagandus

  redis-attention-register:
    image: redis:latest
    container_name: attention-register
    restart: always
    ports:
      - "63793:6379"
    volumes:
      - redis_attention_register_data:/data
    networks:
      - propagandus

  redis-reaction-register:
    image: redis:latest
    container_name: reaction-register
    restart: always
    ports:
      - "63794:6379"
    volumes:
      - redis_reaction_register_data:/data
    networks:
      - propagandus

volumes:
  mysql_data:
  mongo_register:
  mongo_sender:
  redis_persistence_data:
  redis_people_register_data:
  redis_attention_register_data:
  redis_reaction_register_data:

networks:
  propagandus:
    driver: bridge