version: '3.8'

services:
  mariadb-persistence:
    image: mariadb:latest
    container_name: data-persistence-service
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: data-persistence-service
      MARIADB_DATABASE: data-persistence-service
      MARIADB_USER: propagandus
      MARIADB_PASSWORD: propagandus
    ports:
      - "63310:3306"
    volumes:
      - mariadb_persistence_data:/var/lib/mysql
    networks:
      - propagandus

  mongodb-local:
    image: mongo:latest
    container_name: data-local
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: local
      MONGO_INITDB_DATABASE: local-db
    ports:
      - "61000:27017"
    volumes:
      - mongo_local_data:/data
    networks:
      - propagandus

volumes:
  mariadb_persistence_data:
  mongo_local_data:

networks:
  propagandus:
    driver: bridge