version: "3.9"

services:
  mysql-analitics:
    image: mysql:latest
    container_name: data-analitics
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: data-analitics2@
      MYSQL_DATABASE: data-analitics
      MYSQL_USER: propagandus
      MYSQL_PASSWORD: propagandus2@
    ports:
      - "53300:3306"
    volumes:
      - mysql_analitics_data:/var/lib/mysql

  mysql-backup:
    image: mysql:latest
    container_name: data-backup
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: data-backup2@
      MYSQL_DATABASE: data-backup
      MYSQL_USER: propagandus
      MYSQL_PASSWORD: propagandus2@
    ports:
      - "53301:3306"
    volumes:
      - mysql_backup_data:/var/lib/mysql

  mongodb-reciver:
    image: mongo:latest
    container_name: data-reciver
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: data-reciver
      MONGO_INITDB_ROOT_PASSWORD: data-reciver
    ports:
      - "57010:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - propagandus

  redis-analitics:
    image: redis:latest
    container_name: data-analitics-redis
    restart: always
    ports:
      - "63790:6379"
    volumes:
      - redis_analitics_data:/data
    networks:
      - propagandus

  redis-distribution:
    image: redis:latest
    container_name: data-distribution-redis
    restart: always
    ports:
      - "63791:6379"
    volumes:
      - redis_distribution_data:/data
    networks:
      - propagandus

volumes:
  mysql_analitics_data:
  mysql_backup_data:
  mongo_data:
  redis_analitics_data:
  redis_distribution_data:

networks:
  propagandus:
    driver: bridge
