services:
  mariadb-analytics:
    image: mariadb:latest
    container_name: cloud-data-analytics
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: data-analytics
      MARIADB_DATABASE: data-analytics
      MARIADB_USER: propagandus
      MARIADB_PASSWORD: propagandus
    ports:
      - "53300:3306"
    volumes:
      - mariadb_analytics_data:/var/lib/mysql

  mariadb-backup:
    image: mariadb:latest
    container_name: cloud-data-backup
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: data-backup
      MARIADB_DATABASE: data-backup
      MARIADB_USER: propagandus
      MARIADB_PASSWORD: propagandus
    ports:
      - "53301:3306"
    volumes:
      - mariadb_backup_data:/var/lib/mysql

  mongodb-reciver:
    image: mongo:latest
    container_name: cloud-data-reciver
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: data-reciver
      MONGO_INITDB_ROOT_PASSWORD: data-reciver
    ports:
      - "57020:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - propagandus

  redis-analytics:
    image: redis:latest
    container_name: cloud-data-analytics-redis
    restart: always
    ports:
      - "63780:6379"
    volumes:
      - redis_analytics_data:/data
    networks:
      - propagandus

  redis-distribution:
    image: redis:latest
    container_name: cloud-data-distribution-redis
    restart: always
    ports:
      - "63781:6379"
    volumes:
      - redis_distribution_data:/data
    networks:
      - propagandus

volumes:
  mariadb_analytics_data:
  mariadb_backup_data:
  mongo_data:
  redis_analytics_data:
  redis_distribution_data:

networks:
  propagandus:
    driver: bridge