version: "3.9"

services:
  mysql-analitics:
    image: mysql:latest
    container_name: data-analitics
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: data-analitics2@
      MYSQL_DATABASE: data-analitics
      MYSQL_USER: propagandus
      MYSQL_PASSWORD: propagandus2@
    ports:
      - "53300:3306"
    volumes:
      - mysql_analitics_data:/var/lib/mysql

  mysql-backup:
    image: mysql:latest
    container_name: data-backup
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: data-backup2@
      MYSQL_DATABASE: data-backup
      MYSQL_USER: propagandus
      MYSQL_PASSWORD: propagandus2@
    ports:
      - "53301:3306"
    volumes:
      - mysql_backup_data:/var/lib/mysql

  mongodb-distribution:
    image: mongo:latest
    container_name: data-distribution
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: data-distribution
      MONGO_INITDB_ROOT_PASSWORD: data-distribution
    ports:
      - "57010:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - propagandus

volumes:
  mysql_analitics_data:
  mysql_backup_data:
  mongo_data:

networks:
  propagandus:
    driver: bridge
