version: "3.9"

services:
  mariadb-analitics:
    image: mariadb:latest
    container_name: data-analitics
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: data-analitics
      MARIADB_DATABASE: data-analitics
      MARIADB_USER: propagandus
      MARIADB_PASSWORD: propagandus
    ports:
      - "53300:3306"
    volumes:
      - mariadb_analitics_data:/var/lib/mysql

  mariadb-backup:
    image: mariadb:latest
    container_name: data-backup
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: data-backup
      MARIADB_DATABASE: data-backup
      MARIADB_USER: propagandus
      MARIADB_PASSWORD: propagandus
    ports:
      - "53301:3306"
    volumes:
      - mariadb_backup_data:/var/lib/mysql

  mongodb-reciver:
    image: mongo:latest
    container_name: data-reciver
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: data-reciver
      MONGO_INITDB_ROOT_PASSWORD: data-reciver
    ports:
      - "57020:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - propagandus

  redis-analitics:
    image: redis:latest
    container_name: data-analitics-redis
    restart: always
    ports:
      - "63780:6379"
    volumes:
      - redis_analitics_data:/data
    networks:
      - propagandus

  redis-distribution:
    image: redis:latest
    container_name: data-distribution-redis
    restart: always
    ports:
      - "63781:6379"
    volumes:
      - redis_distribution_data:/data
    networks:
      - propagandus

volumes:
  mariadb_analitics_data:
  mariadb_backup_data:
  mongo_data:
  redis_analitics_data:
  redis_distribution_data:

networks:
  propagandus:
    driver: bridge