server:
  port: 41002

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:53352/data-location
    username: propagandus
    password: propagandus
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  data:
    mongodb:
      uri: mongodb://location:location@mongodb-location:57052/location-db
